//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Yottor.UI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARateRequest", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    public partial class CARateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZipCodePlusFourField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZipCodePlusFour {
            get {
                return this.ZipCodePlusFourField;
            }
            set {
                if ((this.ZipCodePlusFourField.Equals(value) != true)) {
                    this.ZipCodePlusFourField = value;
                    this.RaisePropertyChanged("ZipCodePlusFour");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARateResponseCollection", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    public partial class CARateResponseCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Medical.Yottor.UI.ServiceReference1.CARateResponse[] CARateResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisclaimerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersion {
            get {
                return this.AppVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersionField, value) != true)) {
                    this.AppVersionField = value;
                    this.RaisePropertyChanged("AppVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medical.Yottor.UI.ServiceReference1.CARateResponse[] CARateResponses {
            get {
                return this.CARateResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.CARateResponsesField, value) != true)) {
                    this.CARateResponsesField = value;
                    this.RaisePropertyChanged("CARateResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Disclaimer {
            get {
                return this.DisclaimerField;
            }
            set {
                if ((object.ReferenceEquals(this.DisclaimerField, value) != true)) {
                    this.DisclaimerField = value;
                    this.RaisePropertyChanged("Disclaimer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARateResponse", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    public partial class CARateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BufferSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Medical.Yottor.UI.ServiceReference1.CARateRequest CARateRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Medical.Yottor.UI.ServiceReference1.Error[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Medical.Yottor.UI.ServiceReference1.RateInformation[] ResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermsOfUseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BufferSize {
            get {
                return this.BufferSizeField;
            }
            set {
                if ((this.BufferSizeField.Equals(value) != true)) {
                    this.BufferSizeField = value;
                    this.RaisePropertyChanged("BufferSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medical.Yottor.UI.ServiceReference1.CARateRequest CARateRequest {
            get {
                return this.CARateRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.CARateRequestField, value) != true)) {
                    this.CARateRequestField = value;
                    this.RaisePropertyChanged("CARateRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medical.Yottor.UI.ServiceReference1.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.ResponseDateField;
            }
            set {
                if ((this.ResponseDateField.Equals(value) != true)) {
                    this.ResponseDateField = value;
                    this.RaisePropertyChanged("ResponseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medical.Yottor.UI.ServiceReference1.RateInformation[] Responses {
            get {
                return this.ResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsesField, value) != true)) {
                    this.ResponsesField = value;
                    this.RaisePropertyChanged("Responses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermsOfUse {
            get {
                return this.TermsOfUseField;
            }
            set {
                if ((object.ReferenceEquals(this.TermsOfUseField, value) != true)) {
                    this.TermsOfUseField = value;
                    this.RaisePropertyChanged("TermsOfUse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateInformation", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    public partial class RateInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Medical.Yottor.UI.ServiceReference1.RateDetails DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medical.Yottor.UI.ServiceReference1.RateDetails Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateDetails", Namespace="http://services.gis.boe.ca.gov/api/taxrates")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.CARateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.CARateResponseCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.CARateResponse[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.CARateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.Error[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.RateInformation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medical.Yottor.UI.ServiceReference1.RateInformation))]
    public partial class RateDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalcMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JurisdictionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TACField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalcMethod {
            get {
                return this.CalcMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.CalcMethodField, value) != true)) {
                    this.CalcMethodField = value;
                    this.RaisePropertyChanged("CalcMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Confidence {
            get {
                return this.ConfidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidenceField, value) != true)) {
                    this.ConfidenceField = value;
                    this.RaisePropertyChanged("Confidence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jurisdiction {
            get {
                return this.JurisdictionField;
            }
            set {
                if ((object.ReferenceEquals(this.JurisdictionField, value) != true)) {
                    this.JurisdictionField = value;
                    this.RaisePropertyChanged("Jurisdiction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAC {
            get {
                return this.TACField;
            }
            set {
                if ((object.ReferenceEquals(this.TACField, value) != true)) {
                    this.TACField = value;
                    this.RaisePropertyChanged("TAC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gis.boe.ca.gov/api/taxrates", ConfigurationName="ServiceReference1.CATaxRateAPI")]
    public interface CATaxRateAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gis.boe.ca.gov/api/taxrates/CATaxRateAPI/Hello", ReplyAction="http://services.gis.boe.ca.gov/api/taxrates/CATaxRateAPI/HelloResponse")]
        string Hello(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gis.boe.ca.gov/api/taxrates/CATaxRateAPI/GetRate", ReplyAction="http://services.gis.boe.ca.gov/api/taxrates/CATaxRateAPI/GetRateResponse")]
        Medical.Yottor.UI.ServiceReference1.CARateResponseCollection GetRate(Medical.Yottor.UI.ServiceReference1.CARateRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CATaxRateAPIChannel : Medical.Yottor.UI.ServiceReference1.CATaxRateAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CATaxRateAPIClient : System.ServiceModel.ClientBase<Medical.Yottor.UI.ServiceReference1.CATaxRateAPI>, Medical.Yottor.UI.ServiceReference1.CATaxRateAPI {
        
        public CATaxRateAPIClient() {
        }
        
        public CATaxRateAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CATaxRateAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CATaxRateAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CATaxRateAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(int value) {
            return base.Channel.Hello(value);
        }
        
        public Medical.Yottor.UI.ServiceReference1.CARateResponseCollection GetRate(Medical.Yottor.UI.ServiceReference1.CARateRequest request) {
            return base.Channel.GetRate(request);
        }
    }
}
